

services:

  db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: school
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - three-tier-net

  backend:
    build: ./backend
    container_name: backend-container
    restart: always
    environment:
      DB_HOST: db         # IMPORTANT â€” DB hostname = service name
      DB_USER: root
      DB_PASSWORD: mysql123
      DB_NAME: school
    ports:
      - "3500:3500"
    depends_on:
      - db
    networks:
      - three-tier-net

  frontend:
    build: ./frontend
    container_name: frontend-container
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - three-tier-net

volumes:
  mysql-data:

networks:
  three-tier-net:
    driver: bridge


